const $=id=>document.getElementById(id), c=SDN11.client;
const esc=s=>String(s??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]));
let cache={rombel:[],eskul:[],activity:[],program:[],news:[],announcement:[],achievement:[],gallery:[],document:[],schedule:[],staging:[]},profile={};
const defs={
rombel:{table:"class_groups",title:"Rombel",fields:[["name","Nama Rombel","text"],["grade","Tingkat","number"],["academic_year","Tahun Ajaran","text"],["semester","Semester","text"],["student_count","Jumlah Siswa","number"],["male_count","Laki-laki","number"],["female_count","Perempuan","number"],["homeroom_teacher","Wali Kelas","text"],["room","Ruang","text"],["source_note","Sumber Data","text"],["published","Tampilkan","checkbox"]]},
eskul:{table:"extracurriculars",title:"Ekstrakurikuler",fields:[["name","Nama Eskul","text"],["day","Hari","text"],["start_time","Jam Mulai","time"],["end_time","Jam Selesai","time"],["location","Lokasi","text"],["coach","Pembina","text"],["trainer","Pelatih","text"],["participant_grades","Kelas Peserta","text"],["capacity","Kuota","number"],["description","Deskripsi","textarea"],["image_url","URL Foto","text"],["image_file","Upload Foto","file"],["active","Aktif","checkbox"]]},
activity:{table:"extracurricular_activities",title:"Kegiatan Eskul",fields:[["extracurricular_id","Eskul","eskul"],["title","Judul","text"],["activity_date","Tanggal","date"],["description","Deskripsi","textarea"],["image_url","URL Foto","text"],["image_file","Upload Foto","file"],["published","Publish","checkbox"]]},
program:{table:"programs",title:"Program Sekolah",fields:[["title","Nama Program","text"],["description","Deskripsi","textarea"],["sort_order","Urutan","number"],["published","Tampilkan","checkbox"]]},
news:{table:"news",title:"Berita",fields:[["title","Judul","text"],["published_at","Tanggal","date"],["excerpt","Ringkasan","textarea"],["content","Isi","textarea"],["image_url","URL Foto","text"],["image_file","Upload Foto","file"],["published","Publish","checkbox"]]},
announcement:{table:"announcements",title:"Pengumuman",fields:[["title","Judul","text"],["published_at","Tanggal","date"],["body","Isi","textarea"],["published","Publish","checkbox"]]},
achievement:{table:"achievements",title:"Prestasi",fields:[["title","Judul","text"],["category","Kategori","text"],["level","Tingkat","text"],["year","Tahun","number"],["description","Deskripsi","textarea"],["published","Publish","checkbox"]]},
gallery:{table:"gallery",title:"Galeri",fields:[["title","Judul Foto","text"],["image_url","URL Foto","text"],["image_file","Upload Foto","file"],["published","Publish","checkbox"]]},
document:{table:"documents",title:"Dokumen",fields:[["title","Nama Dokumen","text"],["category","Kategori","text"],["description","Deskripsi","textarea"],["file_url","URL Dokumen","text"],["file_upload","Upload File","file"],["published","Publish","checkbox"]]},
schedule:{table:"school_schedules",title:"Jadwal",fields:[["day","Hari","text"],["title","Kegiatan/Judul","text"],["time_text","Waktu","text"],["class_name","Kelas","text"],["description","Keterangan","textarea"],["sort_order","Urutan","number"],["published","Publish","checkbox"]]}
};
async function authCheck(){if(!SDN11.configured){$("loginMsg").textContent="Isi konfigurasi Supabase di admin/js/config.js terlebih dahulu.";return}const {data:{session}}=await c.auth.getSession();session?showApp():showLogin()}
function showApp(){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");loadAll()}function showLogin(){$("loginView").classList.remove("hidden");$("appView").classList.add("hidden")}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginMsg").textContent="Memeriksa…";const {error}=await c.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error){$("loginMsg").textContent=error.message;return}$("loginMsg").textContent="";showApp()}
$("logoutBtn").onclick=async()=>{await c.auth.signOut();showLogin()}
async function upload(file,folder){if(!file)return null;const ext=(file.name.split(".").pop()||"bin").toLowerCase();const path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await c.storage.from(SDN11.bucket).upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return c.storage.from(SDN11.bucket).getPublicUrl(path).data.publicUrl}
async function loadAll(){
 const [p,...rs]=await Promise.all([c.from("school_profile").select("*").eq("id",1).maybeSingle(),...Object.values(defs).map(d=>c.from(d.table).select("*").order("created_at",{ascending:false})),c.from("sync_staging").select("*").order("created_at",{ascending:false})]);
 profile=p.data||{}; fillProfile();
 Object.keys(defs).forEach((k,i)=>cache[k]=rs[i].data||[]);cache.staging=rs[Object.keys(defs).length].data||[];
 renderAll();
}
function fillProfile(){const m={schoolName:"name",schoolNpsn:"npsn",schoolStatus:"status",schoolLevel:"level",schoolAccreditation:"accreditation",schoolPrincipal:"principal",schoolStudents:"students",schoolStaff:"staff",schoolAddress:"address",schoolCity:"city",schoolPhone:"phone",schoolEmail:"email",schoolMaps:"maps_url",schoolProfileTitle:"profile_title",schoolDescription:"description",schoolVision:"vision",schoolHeroSubtitle:"hero_subtitle",schoolSpmbTitle:"spmb_title",schoolSpmbUrl:"spmb_url",schoolSpmbDescription:"spmb_description"};for(const [id,k] of Object.entries(m))$(id).value=profile[k]??"";$("schoolMission").value=Array.isArray(profile.mission)?profile.mission.join("\n"):""}
$("saveProfileBtn").onclick=async()=>{const payload={id:1,name:$("schoolName").value,npsn:$("schoolNpsn").value,status:$("schoolStatus").value,level:$("schoolLevel").value,accreditation:$("schoolAccreditation").value,principal:$("schoolPrincipal").value,students:+$("schoolStudents").value||null,staff:+$("schoolStaff").value||null,address:$("schoolAddress").value,city:$("schoolCity").value,phone:$("schoolPhone").value,email:$("schoolEmail").value,maps_url:$("schoolMaps").value,profile_title:$("schoolProfileTitle").value,description:$("schoolDescription").value,vision:$("schoolVision").value,mission:$("schoolMission").value.split("\n").map(x=>x.trim()).filter(Boolean),hero_subtitle:$("schoolHeroSubtitle").value,spmb_title:$("schoolSpmbTitle").value,spmb_url:$("schoolSpmbUrl").value,spmb_description:$("schoolSpmbDescription").value,updated_at:new Date().toISOString()};const {error}=await c.from("school_profile").upsert(payload);$("profileMsg").textContent=error?error.message:"Profil berhasil disimpan.";if(!error){profile=payload;renderAll()}}
function renderAll(){
 $("kpiStudents").textContent=profile.students??"—";$("kpiRombel").textContent=cache.rombel.length;$("kpiEskul").textContent=cache.eskul.length;$("kpiStaging").textContent=cache.staging.filter(x=>x.status==="pending").length;
 for(const k of Object.keys(defs))renderTable(k);renderStaging()
}
function renderTable(type){const d=defs[type],box=$(type+"Editor");const fields=d.fields.filter(f=>f[2]!=="file").slice(0,5);if(!cache[type].length){box.innerHTML='<p class="empty">Belum ada data. Klik “+ Tambah”.</p>';return}box.innerHTML=`<div class="table-wrap"><table class="editor-table"><thead><tr>${fields.map(f=>`<th>${esc(f[1])}</th>`).join("")}<th>Aksi</th></tr></thead><tbody>${cache[type].map(x=>`<tr>${fields.map(f=>`<td>${esc(displayValue(f,x[f[0]]))}</td>`).join("")}<td><div class="editor-actions"><button class="secondary" onclick="openEditor('${type}','${x.id}')">Edit</button><button class="danger" onclick="deleteItem('${type}','${x.id}')">Hapus</button></div></td></tr>`).join("")}</tbody></table></div>`}
function displayValue(f,v){if(f[2]==="checkbox")return v?"Ya":"Tidak";if(f[2]==="eskul"){const x=cache.eskul.find(e=>e.id===v);return x?.name||"-"}return v??"-"}
document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>openEditor(b.dataset.add,null))
window.openEditor=(type,id)=>{const d=defs[type],item=id?cache[type].find(x=>String(x.id)===String(id)):{};$("modalTitle").textContent=(id?"Edit ":"Tambah ")+d.title;$("modalForm").innerHTML=d.fields.map(f=>fieldHTML(f,item[f[0]],type)).join("")+`<div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Batal</button><button class="primary">Simpan</button></div>`;$("modal").classList.remove("hidden");$("modalForm").onsubmit=e=>saveEditor(e,type,id)}
function fieldHTML(f,v,type){const [name,label,kind]=f;if(kind==="checkbox")return `<label class="full"><input type="checkbox" name="${name}" ${v!==false?"checked":""}> ${esc(label)}</label>`;if(kind==="textarea")return `<label class="full">${esc(label)}<textarea name="${name}">${esc(v||"")}</textarea></label>`;if(kind==="file")return `<label class="full">${esc(label)}<input type="file" name="${name}"><span class="file-note">File akan disimpan ke Supabase Storage.</span></label>`;if(kind==="eskul")return `<label>${esc(label)}<select name="${name}" required><option value="">Pilih Eskul</option>${cache.eskul.map(x=>`<option value="${x.id}" ${x.id===v?"selected":""}>${esc(x.name)}</option>`).join("")}</select></label>`;return `<label>${esc(label)}<input type="${kind}" name="${name}" value="${esc(kind==="date"&&v?String(v).slice(0,10):(v??""))}"></label>`}
async function saveEditor(e,type,id){e.preventDefault();const d=defs[type],fd=new FormData(e.target),payload={};for(const f of d.fields){const [name,,kind]=f;if(kind==="file")continue;if(kind==="checkbox")payload[name]=fd.get(name)==="on";else if(kind==="number")payload[name]=fd.get(name)?+fd.get(name):null;else if(kind==="date"&&fd.get(name)&&(["news","announcement"].includes(type)))payload[name]=fd.get(name)+"T00:00:00+07:00";else payload[name]=fd.get(name)||null}
 try{
  const imageFile=fd.get("image_file");if(imageFile&&imageFile.size){payload.image_url=await upload(imageFile,type)}
  const docFile=fd.get("file_upload");if(docFile&&docFile.size){payload.file_url=await upload(docFile,"documents")}
  const req=id?c.from(d.table).update(payload).eq("id",id):c.from(d.table).insert(payload);const {error}=await req;if(error)throw error;closeModal();await loadAll()
 }catch(err){alert(err.message)}
}
window.deleteItem=async(type,id)=>{if(!confirm("Hapus data ini?"))return;const {error}=await c.from(defs[type].table).delete().eq("id",id);if(error)alert(error.message);else await loadAll()}
window.closeModal=()=>$("modal").classList.add("hidden");$("modalClose").onclick=closeModal;$("modal").addEventListener("click",e=>{if(e.target===$("modal"))closeModal()})
$("syncBtn").onclick=async()=>{const url=$("syncUrl").value.trim();if(!url){$("syncResult").innerHTML="<p class='warn'>Masukkan URL endpoint.</p>";return}$("syncResult").innerHTML="<p>Memuat…</p>";try{const r=await fetch(url);if(!r.ok)throw new Error("HTTP "+r.status);const data=await r.json();const {error}=await c.from("sync_staging").insert({source_url:url,payload:data,status:"pending"});if(error)throw error;await c.from("sync_runs").insert({source_url:url,status:"success"});$("syncResult").innerHTML="<p>Data kandidat tersimpan di staging.</p>";await loadAll()}catch(err){await c.from("sync_runs").insert({source_url:url,status:"failed",note:err.message});$("syncResult").innerHTML="<p class='warn'>Gagal: "+esc(err.message)+". Periksa CORS/endpoint.</p>"}}
function renderStaging(){const list=$("stagingList");const pending=cache.staging.slice(0,10);list.innerHTML=pending.length?pending.map(x=>`<div class="staging-item"><b>${esc(x.status)}</b><small>${esc(x.source_url||"")} · ${new Date(x.created_at).toLocaleString("id-ID")}</small><div class="editor-actions">${x.status==="pending"?`<button class="secondary" onclick="setStaging('${x.id}','accepted')">Terima sebagai referensi</button><button class="danger" onclick="setStaging('${x.id}','rejected')">Tolak</button>`:""}</div></div>`).join(""):"<p class='empty'>Belum ada data staging.</p>"}
window.setStaging=async(id,status)=>{const {error}=await c.from("sync_staging").update({status,reviewed_at:new Date().toISOString()}).eq("id",id);if(error)alert(error.message);else await loadAll()}
authCheck();